# Generated by Django 6.0.1 on 2026-01-30 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0002_portfolio_delete_project_delete_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the category"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for icon (e.g., 'fas fa-globe', 'fas fa-mobile-alt')",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#4a6fa5",
                        help_text="Hex color code for category badge",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_in_nav",
                    models.BooleanField(
                        default=True, help_text="Show this category in navigation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="projects/documents/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("documentation", "Documentation"),
                            ("source", "Source Code"),
                            ("design", "Design Files"),
                            ("report", "Project Report"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        default="documentation",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file_size",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Publicly downloadable"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("design", "Design Mockup"),
                            ("diagram", "Diagram/Architecture"),
                            ("wireframe", "Wireframe"),
                            ("other", "Other"),
                        ],
                        default="screenshot",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show as featured image"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-is_featured"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("article", "Article/Blog Post"),
                            ("tutorial", "Tutorial"),
                            ("review", "Review"),
                            ("news", "News Coverage"),
                            ("award", "Award"),
                            ("reference", "Reference"),
                            ("other", "Other"),
                        ],
                        default="reference",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("milestone_date", models.DateField()),
                (
                    "is_major",
                    models.BooleanField(default=False, help_text="Major milestone"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["milestone_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                ("author_title", models.CharField(blank=True, max_length=100)),
                ("author_company", models.CharField(blank=True, max_length=100)),
                (
                    "author_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/authors/"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "-rating", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "tech_type",
                    models.CharField(
                        choices=[
                            ("framework", "Framework/Library"),
                            ("language", "Programming Language"),
                            ("database", "Database"),
                            ("tool", "Tool/Software"),
                            ("service", "Cloud Service"),
                            ("other", "Other"),
                        ],
                        default="framework",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Icon class (e.g., 'fab fa-python', 'fab fa-js-square')",
                        max_length=100,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="technologies/logos/"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Primary brand color in hex",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of title",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Brief one-line description (appears in listings)",
                        max_length=300,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Short summary (2-3 paragraphs, appears on listing cards)"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        help_text="Complete project description with details, challenges, solutions"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("mobile", "Mobile Application"),
                            ("desktop", "Desktop Software"),
                            ("api", "API/Backend Service"),
                            ("library", "Library/Package"),
                            ("plugin", "Plugin/Extension"),
                            ("game", "Game Development"),
                            ("data", "Data Science/AI/ML"),
                            ("iot", "IoT/Embedded"),
                            ("design", "UI/UX Design"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept/Idea"),
                            ("planning", "Planning"),
                            ("development", "In Development"),
                            ("testing", "Testing"),
                            ("completed", "Completed"),
                            ("live", "Live & Maintained"),
                            ("archived", "Archived"),
                            ("on_hold", "On Hold"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured projects appear on homepage"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished projects are not visible to public",
                    ),
                ),
                (
                    "featured_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in featured listings (lower = first)",
                    ),
                ),
                (
                    "concept_date",
                    models.DateField(
                        blank=True,
                        help_text="When the project was conceived",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Development start date", null=True
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, help_text="When project was completed", null=True
                    ),
                ),
                (
                    "launch_date",
                    models.DateField(
                        blank=True, help_text="Public launch date", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        blank=True, help_text="Last significant update", null=True
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Main project image (1200x630px recommended)",
                        null=True,
                        upload_to="projects/featured/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Small thumbnail (400x300px recommended)",
                        null=True,
                        upload_to="projects/thumbnails/",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Project logo/icon",
                        null=True,
                        upload_to="projects/logos/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Link to demo video (YouTube/Vimeo)"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                (
                    "gitlab_url",
                    models.URLField(blank=True, help_text="GitLab repository URL"),
                ),
                ("live_url", models.URLField(blank=True, help_text="Live project URL")),
                ("demo_url", models.URLField(blank=True, help_text="Demo/Preview URL")),
                (
                    "documentation_url",
                    models.URLField(blank=True, help_text="Documentation URL"),
                ),
                (
                    "figma_url",
                    models.URLField(blank=True, help_text="Figma design file URL"),
                ),
                (
                    "behance_url",
                    models.URLField(blank=True, help_text="Behance project URL"),
                ),
                (
                    "download_url",
                    models.URLField(blank=True, help_text="Download link"),
                ),
                ("is_solo_project", models.BooleanField(default=True)),
                (
                    "team_members",
                    models.TextField(
                        blank=True, help_text="Names of team members (one per line)"
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="Client name (if applicable)",
                        max_length=200,
                    ),
                ),
                (
                    "collaboration_notes",
                    models.TextField(
                        blank=True, help_text="Notes about team collaboration"
                    ),
                ),
                (
                    "lines_of_code",
                    models.IntegerField(
                        blank=True, help_text="Approximate lines of code", null=True
                    ),
                ),
                (
                    "development_hours",
                    models.IntegerField(
                        blank=True, help_text="Estimated development hours", null=True
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, help_text="Number of likes"),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of shares"
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True,
                        help_text="Technical challenges faced and how they were overcome",
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(
                        blank=True, help_text="Key lessons learned from this project"
                    ),
                ),
                (
                    "key_features",
                    models.TextField(
                        blank=True, help_text="List of key features (one per line)"
                    ),
                ),
                (
                    "future_improvements",
                    models.TextField(
                        blank=True, help_text="Planned future improvements or features"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("canonical_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_projects",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-is_featured",
                    "featured_order",
                    "-published_at",
                    "-created_at",
                ],
            },
        ),
    ]
