# Generated by Django 6.0.1 on 2026-01-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills_used",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills demonstrated in this project",
                related_name="projects",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary project category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.projectcategory",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="secondary_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional categories",
                related_name="secondary_projects",
                to="projects.projectcategory",
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectlink",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projecttestimonial",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonials",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Technologies used in this project",
                related_name="projects",
                to="projects.technology",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["slug"], name="projects_pr_slug_042165_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "is_published"], name="projects_pr_status_911ccb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_featured", "is_published"],
                name="projects_pr_is_feat_7f1332_idx",
            ),
        ),
    ]
