# Generated by Django 6.0.1 on 2026-01-31 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("africa", "Africa"),
                            ("asia", "Asia"),
                            ("europe", "Europe"),
                            ("north_america", "North America"),
                            ("south_america", "South America"),
                            ("oceania", "Oceania"),
                            ("antarctica", "Antarctica"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("best_time_to_visit", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated cost per person in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="travel/destinations/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TravelTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("packing", "Packing"),
                            ("budget", "Budget"),
                            ("safety", "Safety"),
                            ("transport", "Transport"),
                            ("accommodation", "Accommodation"),
                            ("food", "Food"),
                            ("culture", "Culture"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "useful_links",
                    models.TextField(
                        blank=True, help_text="Useful links, one per line"
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("adventure", "Adventure"),
                            ("cultural", "Cultural"),
                            ("beach", "Beach"),
                            ("honeymoon", "Honeymoon"),
                            ("family", "Family"),
                            ("solo", "Solo"),
                            ("business", "Business"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration_days", models.IntegerField(help_text="Duration in days")),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.TextField(help_text="List trip highlights, one per line"),
                ),
                (
                    "itinerary",
                    models.TextField(help_text="Detailed day-by-day itinerary"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("featured", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="travel.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="travel/photos/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="travel.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Why you want to visit"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="travel.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "destination")},
            },
        ),
    ]
