# Generated by Django 6.0.1 on 2026-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("content", models.TextField(blank=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("about", "About Section"),
                            ("services", "Services Section"),
                            ("testimonials", "Testimonials Section"),
                            ("contact", "Contact Section"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, upload_to="landing/bg/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
