# Generated by Django 6.0.1 on 2026-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("appetizer", "Appetizer"),
                            ("main", "Main Course"),
                            ("dessert", "Dessert"),
                            ("drink", "Drink"),
                            ("special", "Special"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_spicy", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="dishes/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("calories", models.IntegerField(blank=True, null=True)),
                (
                    "prep_time",
                    models.IntegerField(
                        blank=True, help_text="Preparation time in minutes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Dishes",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Menu Categories",
                "ordering": ["order", "name"],
            },
        ),
    ]
