# Generated by Django 6.0.1 on 2026-01-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuCategory",
        ),
    ]
