# Generated by Django 6.0.1 on 2026-01-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("public_repos", models.IntegerField(default=0)),
                ("followers", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=200)),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["api_name", "endpoint"],
                        name="api_integra_api_nam_1c53d7_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="api_integra_expires_5a4e2e_idx"
                    ),
                ],
            },
        ),
    ]
