# Generated by Django 6.0.1 on 2026-01-30 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0002_portfolio_delete_project_delete_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of this skill category"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome or other icon class (e.g., 'fas fa-code', 'fas fa-paint-brush')",
                        max_length=100,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#4a6fa5",
                        help_text="Hex color for category icon",
                        max_length=20,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#f0f4f8",
                        help_text="Background color for category cards",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_in_chart",
                    models.BooleanField(
                        default=True, help_text="Include this category in skills chart"
                    ),
                ),
                (
                    "show_on_resume",
                    models.BooleanField(
                        default=True, help_text="Show skills in this category on resume"
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Skill name (e.g., Python, React, Photoshop)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of skill name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the skill and your experience with it",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description (appears in tooltips and cards)",
                        max_length=200,
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Skill"),
                            ("soft", "Soft Skill"),
                            ("language", "Programming Language"),
                            ("framework", "Framework/Library"),
                            ("tool", "Tool/Software"),
                            ("database", "Database"),
                            ("cloud", "Cloud/DevOps"),
                            ("design", "Design/UI/UX"),
                            ("methodology", "Methodology"),
                            ("certification", "Certification"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner (1-2 years)"),
                            ("intermediate", "Intermediate (2-4 years)"),
                            ("advanced", "Advanced (4-6 years)"),
                            ("expert", "Expert (6+ years)"),
                            ("master", "Master/Lead (8+ years)"),
                        ],
                        default="intermediate",
                        help_text="Overall proficiency level",
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        default=70,
                        help_text="Proficiency percentage (1-100)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        help_text="Years of experience with this skill",
                        max_digits=3,
                    ),
                ),
                (
                    "last_used",
                    models.DateField(
                        blank=True,
                        help_text="When you last used this skill professionally",
                        null=True,
                    ),
                ),
                (
                    "first_learned",
                    models.DateField(
                        blank=True,
                        help_text="When you first learned this skill",
                        null=True,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Icon class (e.g., 'fab fa-python', 'fab fa-react', 'fas fa-database')",
                        max_length=100,
                    ),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        help_text="Custom icon/image for the skill",
                        null=True,
                        upload_to="skills/icons/",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Official technology logo",
                        null=True,
                        upload_to="skills/logos/",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#3498db",
                        help_text="Primary color for skill badge (hex code)",
                        max_length=20,
                    ),
                ),
                (
                    "gradient_start",
                    models.CharField(
                        blank=True,
                        help_text="Gradient start color (for progress bars)",
                        max_length=20,
                    ),
                ),
                (
                    "gradient_end",
                    models.CharField(
                        blank=True,
                        help_text="Gradient end color (for progress bars)",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured skills appear on homepage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active skills are visible in portfolio"
                    ),
                ),
                (
                    "show_on_resume",
                    models.BooleanField(
                        default=True, help_text="Include this skill in resume/CV"
                    ),
                ),
                (
                    "show_in_chart",
                    models.BooleanField(
                        default=True, help_text="Include in skills proficiency chart"
                    ),
                ),
                (
                    "featured_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in featured listings (lower = first)",
                    ),
                ),
                (
                    "resume_order",
                    models.IntegerField(
                        default=0, help_text="Order on resume (lower = first)"
                    ),
                ),
                ("has_certification", models.BooleanField(default=False)),
                ("certification_name", models.CharField(blank=True, max_length=200)),
                (
                    "certification_url",
                    models.URLField(blank=True, help_text="Link to certification"),
                ),
                ("certification_date", models.DateField(blank=True, null=True)),
                ("certification_expiry", models.DateField(blank=True, null=True)),
                (
                    "project_count",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of projects using this skill (auto-calculated)",
                    ),
                ),
                (
                    "notable_achievements",
                    models.TextField(
                        blank=True,
                        help_text="Notable achievements or projects using this skill",
                    ),
                ),
                (
                    "best_for",
                    models.TextField(
                        blank=True,
                        help_text="What this skill is best suited for (one per line)",
                    ),
                ),
                (
                    "limitations",
                    models.TextField(
                        blank=True,
                        help_text="Known limitations or areas for improvement",
                    ),
                ),
                (
                    "official_website",
                    models.URLField(
                        blank=True, help_text="Official technology website"
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(blank=True, help_text="Official documentation"),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, help_text="GitHub repository/organization"
                    ),
                ),
                (
                    "learning_resource",
                    models.URLField(
                        blank=True, help_text="Recommended learning resource/tutorial"
                    ),
                ),
                (
                    "marketplace_url",
                    models.URLField(
                        blank=True,
                        help_text="Marketplace/profile (e.g., npm, PyPI, Docker Hub)",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of profile views"
                    ),
                ),
                (
                    "interest_score",
                    models.IntegerField(
                        default=50,
                        help_text="Current interest level in using this skill (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "market_demand",
                    models.CharField(
                        choices=[
                            ("low", "Low Demand"),
                            ("medium", "Medium Demand"),
                            ("high", "High Demand"),
                            ("very_high", "Very High Demand"),
                        ],
                        default="medium",
                        help_text="Current market demand for this skill",
                        max_length=20,
                    ),
                ),
                (
                    "current_version",
                    models.CharField(
                        blank=True, help_text="Current/latest version", max_length=50
                    ),
                ),
                (
                    "typical_use_case",
                    models.TextField(
                        blank=True, help_text="Typical use cases for this skill"
                    ),
                ),
                (
                    "alternatives",
                    models.TextField(
                        blank=True, help_text="Alternative technologies/skills"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_assessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this skill was last assessed/updated",
                        null=True,
                    ),
                ),
                (
                    "complementary_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Skills that complement/are used with this skill",
                        to="skills.skill",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_skills",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary skill category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills",
                        to="skills.skillcategory",
                    ),
                ),
                (
                    "secondary_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional categories",
                        related_name="secondary_skills",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "resume_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon_class", models.CharField(blank=True, max_length=100)),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="skills/badges/"
                    ),
                ),
                ("earned_date", models.DateField()),
                ("issuer", models.CharField(blank=True, max_length=100)),
                ("verification_url", models.URLField(blank=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_date"],
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon_class", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(default="#6c5ce7", max_length=20)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="skills.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillProficiencyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_proficiency",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "new_proficiency",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Reason for change or assessment notes"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiency_history",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proficiency History",
                "verbose_name_plural": "Proficiency History",
                "ordering": ["-change_date"],
            },
        ),
        migrations.CreateModel(
            name="SkillRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("complementary", "Complementary Skill"),
                            ("next_level", "Next Level Skill"),
                            ("alternative", "Alternative Technology"),
                            ("specialization", "Specialization"),
                            ("prerequisite", "Prerequisite"),
                        ],
                        default="complementary",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why this skill is recommended"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_by",
                        to="skills.skill",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "recommendation_type"],
            },
        ),
        migrations.CreateModel(
            name="SkillAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_date", models.DateField()),
                (
                    "theoretical_knowledge",
                    models.IntegerField(
                        default=5,
                        help_text="Theoretical understanding (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "practical_experience",
                    models.IntegerField(
                        default=5,
                        help_text="Hands-on experience (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "problem_solving",
                    models.IntegerField(
                        default=5,
                        help_text="Problem-solving ability (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "teaching_ability",
                    models.IntegerField(
                        default=5,
                        help_text="Ability to teach others (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Assessment notes and observations"
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True, help_text="Learning goals for next assessment"
                    ),
                ),
                ("next_assessment_date", models.DateField(blank=True, null=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date"],
                "unique_together": {("skill", "assessment_date")},
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["slug"], name="skills_skil_slug_2fd1f3_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="skills_skil_is_acti_72b18b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["proficiency", "is_active"],
                name="skills_skil_profici_8d41f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["skill_type", "is_active"],
                name="skills_skil_skill_t_de85aa_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillrecommendation",
            unique_together={("skill", "recommended_skill")},
        ),
    ]
