# Generated by Django 6.0.1 on 2026-01-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["category", "name"], "verbose_name_plural": "Dishes"},
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="available",
            new_name="is_available",
        ),
        migrations.AddField(
            model_name="dish",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dishes/"),
        ),
        migrations.AddField(
            model_name="dish",
            name="is_spicy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dish",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dish",
            name="prep_time",
            field=models.IntegerField(
                blank=True, help_text="Preparation time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.CharField(
                choices=[
                    ("appetizer", "Appetizer"),
                    ("main", "Main Course"),
                    ("dessert", "Dessert"),
                    ("drink", "Drink"),
                    ("special", "Special"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=200)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("header", "Header Menu"),
                            ("footer", "Footer Menu"),
                            ("social", "Social Menu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("icon_class", models.CharField(blank=True, max_length=50)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_type", "order", "title"],
            },
        ),
    ]
